# This workflow builds a release AAB and APK for the Vuvur Android app.
# It is triggered manually from the GitHub Actions tab.

name: Android Release Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the correct JDK version (17 is required)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          # ✅ Change the Java version from 11 to 17
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Make the Gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Step 4: Build the Android App Bundle (AAB)
      # Note: For a real Play Store release, you must sign your app.
      # This would involve adding a signingConfigs block to your build.gradle.kts
      # and using GitHub Secrets to store your keystore and passwords.
      - name: Build AAB
        run: ./gradlew :app:bundleRelease

      # Step 5: Build the APK
      - name: Build APK
        run: ./gradlew :app:assembleRelease

      # Step 6: Upload the generated APK as a build artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk